### ISSUE TITLE
When Jonas-user submit url - NOT OK recieved

### ISSUE THREAD

**Issue by Arxcis** [technocake/SigmaPrototype#1]
Mac osx 10.10
link tried: https://github.com/technocake/SigmaPrototype/issues/2

https://github.com/technocake/SigmaPrototype/blob/master/__init__.py#L91-L102

**Comment by Arxcis** [comment]
Robin gets OK ?!?!?!

**Comment by technocake** [comment]
It was using statically typed username language. Fixed now

On Tuesday, August 9, 2016, Jonas <notifications@github.com> wrote:
> Robin gets OK ?!?!?!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/MO9EN7UojGd9P3JJd7-ZwA0K9ripDvH0GQUci-pUuyv5vB3j3PgTaNfwm9dJXFjIexOdttZ0Ablf1k8MlTY-JFxVueb74WVjcNnkecHlrW1dRIg6M6KUUgzV7i71QlVbAJ-Zo1B3VcbAfhJFHfJYvRmaPT_P5w=s0-d-e1-ft#https://github.com/notifications/beacon/ABGUq8lPbB2BNc14tEnsIPrvpl_uZazCks5qeLWugaJpZM4JgTwT.gif>
