### ISSUE TITLE
Client - Todays mission - Implement the following core features 

### ISSUE THREAD

**Issue by Arxcis** [technocake/SigmaPrototype#10]
- Search urls
- Edit topics
- Delete urls
- Autocomplete topics
- Make topics NOT case-sensitive

**Comment by technocake** [comment]
backend implemented:
  - relabel topics 
 - delete urls

**Comment by Arxcis** [comment]
- All these features are now implemented. Considered it closed 👍

**Comment by technocake** [comment]
/relabel is behaving as expected, it does not expect url as a parameter, only old and new subtopic texts. 
Use /moveurl instead https://github.com/technocake/SigmaPrototype/blob/master/DOCS/sigma-api/moveurl.md

**Comment by Arxcis** [comment]
Great. I will look into it.

17. aug. 2016 20.05 skrev "Robin Garen Aaberg" <notifications@github.com>:

**Comment by Arxcis** [comment]
Using /moveurl now
