### ISSUE TITLE
Get_maps not JSON serializeable

### ISSUE THREAD

**Issue by Arxcis** [technocake/SigmaPrototype#11]
Ideally I want a JSON-list of all the maps connected to a user, so I can use them to make a navigation element, to switch between maps.

New @app.route created -- http://localhost:5000/getmaps

In __init__.py i tried:
---- 1 -----
the_maps = sigma.get_maps(user).values()
JSON(maps = the_maps)
ERROR: "status": "Getmaps error:dict_values([sigma.KnowledgeMap object at 0x1099f5a58, sigma.KnowledgeMap object at 0x1099f5eb]) is not JSON serializable" 

---- 2 -----
 the_maps = sigma.get_maps(user)
JSON(maps = the_maps. __ dict __ )
  ERROR: "status": "Getmaps error:'dict' object has no attribute ' __ dict __ '"
 
---- 3 ------
the_maps = sigma.get_maps(user)
JSON(maps = the_maps)
ERROR - "status": "Getmaps error:sigma.KnowledgeMap object at 0x10e427a58 is not JSON serializable"

**Comment by Arxcis** [comment]
---- 4 ----
the_maps = sigma.get_maps(user).keys()
JSON(maps=the_maps)
ERROR:  "status": "Getmaps error:dict_keys(['HTML5', 'Games programming', 'html', 'Tutorials', 'API']) is not JSON serializable"

**Comment by Arxcis** [comment]
Fixed issue by extracting keys in a for-loop. Jahuuu

**Comment by technocake** [comment]
Smood! Think this might have fixed the issue #13 I just opened too. Won't
check now.
