### ISSUE TITLE
Topic not serializable for json

### ISSUE THREAD

**Issue by technocake** [technocake/SigmaPrototype#13]
Occasionally a serialisation error occurs when json serializing KnowledgeMap objects, as the subtopics now contains Topic instances instead of plain string values.

**Comment by Arxcis** [comment]
The buttons in testsvg.html now work, so it is possible to switch between the maps on the fly. But only half of the maps work. The rest of the maps return this error when called upon.

**Comment by technocake** [comment]
This works now
