### ISSUE TITLE
/getmap is using url-form-encoded instead of application/json

### ISSUE THREAD

**Issue by technocake** [technocake/SigmaPrototype#15]
/getmap was implemented as a post, emulating the posting of a html form. 

The rest of the API is using application/json packages. This should be made consistent here too. 
Solving this issue will affect all client side requests of  /getmap.

**Comment by Arxcis** [comment]
We should also look into standardizing , if we use get or fetch. Now we use both, and they kinda mean the excact same thing dont they?

**Comment by technocake** [comment]
Fetch kinda denoted fetching something new like links data, while as get
denoted getting something we already have, like map data. However, I vote
for a more intuitive simpler language by only using get.

On Monday, August 15, 2016, Jonas Solsvik <notifications@github.com> wrote:
> We should also look into standardizing , if we use get or fetch. Now we
use both, and they kinda mean the excact same thing dont they?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/T3d2bFWG4W7fP0rhAvc9wA_k3AGrclguSUEeT_PUsRgO8HMQOgS7zAo7-WcbVdTo4Xtk1iPZUkL6u9guQvAM2XsLn1edVZ-KZmGO49JT2Q8I0IqnwiNCeHT6YiHLnvKUxuJcfHwvqT_cqWSktCvN6o61R7F7lQ=s0-d-e1-ft#https://github.com/notifications/beacon/ABGUq0QXVSntt7yPKUWmRaP-D1Y0463Zks5qf7xlgaJpZM4JjvMM.gif>

**Comment by Arxcis** [comment]
Ahaa:) i understand... Theres is a slight semantic difference. Question is:
is it worth the loss of simplicity? Im am not sure which one to go for
anymore.

15. aug. 2016 6.24 p.m. skrev "Robin Garen Aaberg" <notifications@github.com
