### ISSUE TITLE
Unable to fetch URL data on localhost

### ISSUE THREAD

**Issue by Dynode** [technocake/SigmaPrototype#28]
From dev. console log in Firefox 48:
Valid URL entered!inputurl:237:4
fetching title and metadata...inputurl:233:3
Status: Fetchmeta ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

Seems to be related to be related to problems with PIP described in http://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi# and http://stackoverflow.com/questions/34316951/install-anaconda-library-from-a-local-source
Seems there is no real solution, just workarounds.
Using PTVS (https://microsoft.github.io/PTVS/), Win. 7 x64.

**Comment by technocake** [comment]
Closing this now, and working with fixing this together with Dynode privately.
