### ISSUE TITLE
update() in KnowledgeMap class does not add url to topic.urls when passed as parameter

### ISSUE THREAD

**Issue by kongenfloat** [technocake/SigmaPrototype#30]

**Comment by technocake** [comment]
Looked into this now, and I belive this has to do with the order of doing things in converter.py.
The only place I could see use the add_url method was in line 71.
https://github.com/technocake/SigmaPrototype/blob/master/converter.py#L70-L71
```python
new_map.update(last_topic, text)
last_topic.add_url(text)
```

However, the order of these two lines should be switch. The first line adds a Topic instance to the KnowledgeMap. This topic instance will be added as a  copy inside the knowledgemap.  The local Topic instance "last_topic" is now independent of the copy living inside the knowledge map. So changing the url on last_topic will not affect the status of the copy in the map. 

Suggested solution:
```python
last_topic.add_url(text)
new_map.update(last_topic, text)
```

I will leave it to Andre to have the honor of fixing / closing this issue ;)
