### ISSUE TITLE
Store topics - and make use of them in the representation of links

### ISSUE THREAD

**Issue by Arxcis** [technocake/SigmaPrototype#4]
The idea is that the user decides a main topic and a sub topic when storing a link. 
 This effectively creates a 2 level hierarchy of links in the database. 
  This can be used to present links in a meaningful way.

Every main topic has a sub topic, and the sub topic then connects to all its links.

**Comment by technocake** [comment]
I suggest:
  introduce a dict of maps in a maps file. 


Map: 
   main_topic = [ sub_topics ]
       sub_topic = [ links ]

**Comment by technocake** [comment]
This is now implemented. see DOCS and especially sigam-api/reference.txt

**Comment by Arxcis** [comment]
Well done!:)

11. aug. 2016 04.01 skrev "Robin Garen Aaberg" <notifications@github.com>:
