### ISSUE TITLE
Error with /maps view

### ISSUE THREAD

**Issue by Arxcis** [technocake/SigmaPrototype#9]
- The maps-view switches between 1 and 0 visible maps, everytime i save a new link.
- The visible map is always the latest commited url.

**Comment by technocake** [comment]
Have your tried deleting your old maps files?

**Comment by Arxcis** [comment]
Prøver i morgen

11. aug. 2016 04.02 skrev "Robin Garen Aaberg" <notifications@github.com>:

**Comment by technocake** [comment]
Found the source of error:
  TypeError: __dict__ must be set to a dict

**Comment by technocake** [comment]
Issue solved, the sigma.get_maps() was returning KnowledgeMaps and not __dicts__. Accounted for now internaly in the backend.
